#!/bin/bash

fallocate -l 2GB /swapfile

chmod 600 /swapfile

mkswap /swapfile

swapon /swapfile

echo /swapfile none swap default 0 0 >> /etc/fstab


ln -sf /usr/share/zoneinfo/Asia/Ho_Chi_Minh /etc/localtime

hwclock --systohc

echo en_US.UTF-8 UTF-8 >> /etc/locale.gen

locale-gen

touch /etc/locale.conf

echo LANG=en_US.UTF-8 >> /etc/locale.conf

touch /etc/hostname

echo arch >> /etc/hostname

echo 127.0.0.1	  localhost >> /etc/hosts
echo ::1		      localhost >> /etc/hosts
echo 127.0.1.1	  arch.localdomain  arch

pacman -S man-db man-pages texinfo inetutils netctl dhcpcd networkmanager wpa_supplicant dialog linux-headers network-manager-applet grub efibootmgr os-prober mtools

grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB

grub-mkconfig -o /boot/grub/grub.cfg

passwd
