#!/usr/bin/env bash

ln -sfn ~/dotfiles/.config ~/.config
ln -sfn ~/dotfiles/.scripts ~/.scripts
ln -sf ~/dotfiles/.zshenv ~/.zshenv
ln -sf ~/dotfiles/.gitconfig ~/.gitconfig
ln -sf ~/dotfiles/.profile ~/.profile
